### PR TITLE
Add statistics

### PR DESCRIPTION
**Pull request by PhilippMatthes**
I implemented a first version of admin statistics. They are already showing the solutions, filtered by the current request filter. The statistics now have to be outsourced into a separate class and tested as far as possible. Then I will add some more statistics. @martinmo here is a first screenshot:

bildschirmfoto 2018-06-05 um 13 29 15

### CODE REVIEW

**Comment by PhilippMatthes** [comment]
Travis is currently not building, because there are some style issues with the code. I will fix this later when the PR is ready-to-merge or more advanced.

**Comment by PhilippMatthes** [comment]
With commit #58666cd, I just introduced two new charts into the solutions page. The selfexplanitory "Tries until solution passed" chart and the "hotspot" chart, which shows how many submissions there were for a specific task and how many of them succeeded. With the latter, you will be able to analyze the difficulty and popularity of the tasks. Here is a screenshot from the current state:

bildschirmfoto 2018-06-05 um 16 12 28

**Comment by PhilippMatthes** [comment]
@martinmo I am looking forward for your code review.

**Comment by PhilippMatthes** [comment]
As discussed, I will implement more tests for the statistics now via "Mixins"

**Comment by PhilippMatthes** [comment]
@martinmo the tests for the statistics are now online. Looking forward to your review!

**Comment by martinmo** [comment]
Looks good so far, I've squashed all commits into one and force pushed this branch in order to get rid of the noise. Once the checks finish I will merge this PR :+1:

**Pull request merged**
