### PR TITLE
Add code style checks framework

### LINKED ISSUE #253: Framework for code quality checks
Currently, the complete logic to determine the code quality grade is hidden in the template. However, it should be part of the model. The framework must be designed in such a way that adding a new quality checker does not require us to change existing templates or views.

### LINKED ISSUE #313: Improve test coverage of the checkstyle report parser

### PR DESCRIPTION
**Pull request by PhilippMatthes**
Closes: #253, Fixes: #313.

- [x] Add code style framework models and html
- [x] Use framework to replace current jUnit TestCase rendering
- [x] Use framework to replace CheckstyleData
- [x] Add tests for the new framework
- [x] Add documentation for the new framework

### CODE REVIEW

**Comment by PhilippMatthes** [comment]
@martinmo I took your side suggestions of today's meeting and started to create a reusable code quality check framework. 
I initially wanted to close #313 independently from #253 as we discussed, but I came to the conclusion, that the current `CheckstyleData` class is very hard to test, and it is very hard to find **meaningful** tests. Furthermore, the functions in the `checkstyle.py` file are very hard to understand, though they are extensively documented and though I wrote them myself in the very beginning of my work on INLOOP.
Therefore, the `CheckstyleData` class will be completely replaced by the new framework, with the goal to better test coverage and more reusability. If i had addressed #313 first, it would probably have meaned that sooner or later, most of my new tests would be removed anyways. 
I already was able to get the checkstyle to be shown correctly with the current implementation of the framework.

**Comment by PhilippMatthes** [comment]
Here is the current workstate:

the framework is almost finished and just needs extensive testing and some documentation. All old junit/checkstyle parsing files were removed and replaced with the new `Generators`. In the frontend, nothing visibly changed, but both jUnit and Checkstyle tabs are now fully rendered by the framework.

Bildschirmfoto 2019-08-10 um 08 55 21
Bildschirmfoto 2019-08-10 um 08 47 42

Here is an outline of the framework.
- All partial alerts (such as failed/passed testcases or style issues) are represented by `Alerts`.
- Alerts can be inherited efficiently to suit new purposes and rendered directly into the template by the Mixin `Renderable`. Alerts therefore can be viewed as parts of a view.
- Certain Alerts, such as `CheckstyleAlert` can use a `Severity` to emphasize their importance.
- The newly introduced `Generators` generate the alerts (by `yield`). With `AbstractXMLStringAlertGenerator`, a convenience wrapper for XML files is introduced, which helps  by parsing XML Strings into DOM elements.
- In our use case, `AbstractXMLStringAlertGenerator` can be used to create our own, custom generators to `yield` the partial `Alerts`, which are then rendered directly in the template. DOM parsing is done by the `defusedxml` package `minidom`to prevent malicious XML from being parsed. Of course, a test for this must be reintroduced.

**Comment by PhilippMatthes** [comment]
The framework is now ready for the first review. Test coverage for the newly introduced framework is at 100%.

**Comment by martinmo** [comment]
Wow, this looks very promising. Thanks for the contribution! I still have to think about it, though, and it might take some days for my initial review. (For example, I need to order some of my design ideas and try integrate them with your proposal.) And there are some opportunities to simplify things further, as always ;) But overall, excellent work @PhilippMatthes  :+1::+1::+1:

**Comment by martinmo** [comment]
And: extra 🐝 (Fleißbienchen) for the disciplined commit and testing strategy :-)

**Review by martinmo — COMMENTED** [review]
Thanks for coming up with a prototype of how this could look like. I see this PR as a nice little "design study" which we can learn from, but with respect to merging right now, I think it is not mature enough yet and we probably need several iterations to come to a satisfactory solution. Note that this is quite a difficult feature and I didn't expect the first prototype to be a success.

Reasons are manyfold and hard to explain in a few paragraphes here. I would like to discuss this with you in person. Of course, there are already some parts that are good enough to be kept, especially the test cases.

Because `master` deviated so much in the meantime and there are conflicts, I'll close this PR. It will be easier to create a new branch and cherry-pick the parts we need. Please do not remove this branch yet!

**Pull request closed without merging**
