### PR TITLE
Add solution upload integration tests

### PR DESCRIPTION
**Pull request by PhilippMatthes**
Fixes: #245 

The following tests should be added by this PR:

- [x] Is static and dynamic media displayed correctly?
- [x] Does the solution upload work?
- [ ] Do invalid solutions fail, do valid solutions succeed?
- [ ] (Applicable in the future after merge of https://github.com/st-tu-dresden/inloop/pull/282 and a subsequent rebase of [245-integration-tests](https://github.com/st-tu-dresden/inloop/tree/245-integration-tests) on master: can ZIPs be downloaded?)

### CODE REVIEW

**Comment by martinmo** [comment]
One comment before you put too much effort into it: it is enough when we have just *one* simple upload test, just to see if all the components are wired together correctly. All the details and corner cases are (or should be) already tested as part of the unit tests.

**Comment by martinmo** [comment]
The same applies to the other points. A simple as possible test for each is enough.

**Comment by PhilippMatthes** [comment]
@martinmo which functionalities should be tested to validate that "valid solutions succeed" and "invalid solutions fail"? Should I model a complete validation flow (create solution, run tests, see if the solution succeeded) or can I cut corners on this, regarding the already sufficient test coverage on the testrunner?

**Comment by martinmo** [comment]
This seems to be enough for the time being :+1:

**Pull request merged**
