### PR TITLE
Improve grading test coverage

### PR DESCRIPTION
**Pull request by PhilippMatthes**
- Add multiple test cases
- Add a temp. media root test case
- Apply temp. media root test case to existing tests
- Add a bonus points export wrapper

This branch is based on current master and contains the changes of https://github.com/st-tu-dresden/inloop/pull/279.

### CODE REVIEW

**Comment by martinmo** [comment]
When I run the tests on my machine, after locally merging this branch into master, I get an IntegrityError.

```
======================================================================
ERROR: setUpClass (tests.integration.test_solution_upload.SolutionUploadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/martin/.local/share/virtualenvs/inloop-e56o4yID/lib/python3.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/martin/.local/share/virtualenvs/inloop-e56o4yID/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: tasks_category.id

The above exception was the direct cause of the following exception:
[...]
```

**Comment by PhilippMatthes** [comment]
Will look into it.

**Comment by PhilippMatthes** [comment]
The test failed because `SolutionsData` already provides a `Category` with id `1337`. Therefore, the `UNIQUE` constraint on this attribute fails on creation.

**Comment by martinmo** [comment]
> The test failed because SolutionsData already provides a Category with id 1337. Therefore, the UNIQUE constraint on this attribute failed on creation.

Why are `id`s manually assigned anyway? They should be generated automatically by the Django ORM.

**Pull request merged**
