### PR TITLE
Frontend improvements

### PR DESCRIPTION
**Pull request by PhilippMatthes**
To update our frontend, I introduced a clear and minimal color scheme. Breadcrumbs, links and highlighted text are now shown in a bright blue. The navigation bar is now in a flat dark grey color. I changed the upload zone to look more inviting, with a blue dashed outline. @martinmo you can check out this design, so we can talk about it when we meet. Here are some screenshots:

bildschirmfoto 2018-05-08 um 10 29 04
bildschirmfoto 2018-05-08 um 10 28 42
bildschirmfoto 2018-05-08 um 10 28 28

### CODE REVIEW

**Comment by PhilippMatthes** [comment]
@martinmo please merge this PR only if the Pull Requests [https://github.com/st-tu-dresden/inloop/pull/213](https://github.com/st-tu-dresden/inloop/pull/213) and [https://github.com/st-tu-dresden/inloop/pull/208](https://github.com/st-tu-dresden/inloop/pull/208) were merged. This Pull Request contains code from both pull requests.

**Comment by PhilippMatthes** [comment]
I designed a Logo and inserted it in the INLOOP page. It contains versions for iOS, Android and Windows phone as well.
bildschirmfoto 2018-05-08 um 11 29 16
Here is the favicon I designed:
inloop-favicon
And the INLOOP Logo as is:
inloop-400px-inverted

**Comment by PhilippMatthes** [comment]
Here is the new logo on XCode's iOS Simulator:

bildschirmfoto 2018-05-08 um 11 48 21

**Comment by martinmo** [comment]
This looks very good :+1: I'm looking forward to your live demo!

> @martinmo please merge this PR only if the Pull Requests #213 and #208 were merged. This Pull Request contains code from both pull requests.

Yes, once they are merged, this branch needs to be rebased on the updated master so it will only contain the new changes.

**Comment by PhilippMatthes** [comment]
One last thing, I changed the outputs of the quality reports. Since INLOOP could be used for professional environments and not just in education, I changed the outputs to be more professional and less evaluative. Here are some examples:
bildschirmfoto 2018-06-26 um 11 38 15
bildschirmfoto 2018-06-26 um 11 37 49
bildschirmfoto 2018-06-26 um 11 37 32
bildschirmfoto 2018-06-26 um 11 37 17

**Comment by PhilippMatthes** [comment]
@martinmo the travis build failed due to a network error, if I read that correctly. How can I restart the travis build?
```
Step 1/4 : FROM alpine
Get https://registry-1.docker.io/v2/: EOF
make: *** [init] Error 1
The command "make" failed and exited with 2 during .
```

**Comment by martinmo** [comment]
Superseded by #223.

**Pull request closed without merging**
